import { promises as fs } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import sharp from 'sharp';

const root = process.cwd();
const curationPath = path.join(root, 'src', 'data', 'photo-curation.json');
const outputRoot = path.join(root, 'public', 'images');
const dataPath = path.join(root, 'src', 'data', 'images.generated.ts');

const variants = [
  { key: 'thumbnail', width: 480, quality: 78 },
  { key: 'mobile', width: 840, quality: 82 },
  { key: 'desktop', width: 1280, quality: 84 },
  { key: 'large', width: 1920, quality: 86 },
];

const propertyLabel = (id) => (id === 'casa' ? 'Casa La Arbolada' : 'Departamento La Arbolada');

async function processFile(file) {
  const sourcePath = path.join(root, file.source);
  const metadata = await sharp(sourcePath).rotate().metadata();
  if (!metadata.width || !metadata.height) {
    throw new Error(`No se pudieron obtener las dimensiones de ${file.source}.`);
  }

  const folder = path.join(outputRoot, file.property);
  await fs.mkdir(folder, { recursive: true });

  const sources = {};
  for (const variant of variants) {
    if (variant.key === 'large' && metadata.width < 1600) continue;
    const outputName = `${file.id}-${variant.key}.webp`;
    await sharp(sourcePath)
      .rotate()
      .resize({ width: variant.width, withoutEnlargement: true, fit: 'inside' })
      .webp({ quality: variant.quality, smartSubsample: true })
      .toFile(path.join(folder, outputName));
    sources[variant.key] = `/images/${file.property}/${outputName}`;
  }

  return {
    id: file.id,
    property: file.property,
    space: 'Fotografía curada',
    spaceNumber: null,
    order: 0,
    originalName: path.basename(file.source),
    width: metadata.width,
    height: metadata.height,
    orientation: metadata.width >= metadata.height ? 'landscape' : 'portrait',
    alt: file.alt,
    sources,
    focalPoint: file.focalPoint,
  };
}

function renderData(images) {
  return `// This file is generated by scripts/process-images.mjs. Do not edit manually.\n\nexport type FocalPoint = {\n  desktop: { x: number; y: number };\n  mobile: { x: number; y: number };\n};\n\nexport type PropertyImage = {\n  id: string;\n  property: 'casa' | 'departamento';\n  space: string;\n  spaceNumber: number | null;\n  order: number;\n  originalName: string;\n  width: number;\n  height: number;\n  orientation: 'landscape' | 'portrait' | 'square';\n  alt: string;\n  sources: { thumbnail: string; mobile: string; desktop: string; large?: string };\n  focalPoint?: FocalPoint;\n};\n\nexport const propertyImages: PropertyImage[] = ${JSON.stringify(images, null, 2)} as PropertyImage[];\n\nexport const casaImages = propertyImages.filter((image) => image.property === 'casa');\nexport const departamentoImages = propertyImages.filter((image) => image.property === 'departamento');\n`;
}

async function main() {
  const selection = JSON.parse(await fs.readFile(curationPath, 'utf8'));
  const ids = new Set();
  for (const file of selection) {
    if (ids.has(file.id)) throw new Error(`La selección tiene un id duplicado: ${file.id}.`);
    ids.add(file.id);
    if (!['casa', 'departamento'].includes(file.property)) {
      throw new Error(`Propiedad inválida para ${file.id}.`);
    }
    await fs.access(path.join(root, file.source));
  }

  const images = [];
  for (let index = 0; index < selection.length; index += 1) {
    const image = await processFile(selection[index]);
    images.push(image);
    console.log(`[${index + 1}/${selection.length}] ${image.originalName} → ${propertyLabel(image.property)}`);
  }
  await fs.writeFile(dataPath, renderData(images));
  console.log(`Procesadas ${images.length} fotografías curadas.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
