import { promises as fs } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import decodeHeic from 'heic-decode';
import sharp from 'sharp';

const root = process.cwd();
const inventoryPath = path.join(root, 'reports', 'drive-inventory.json');
const outputRoot = path.join(root, 'public', 'images');
const dataPath = path.join(root, 'src', 'data', 'images.generated.ts');

const variants = [
  { key: 'thumbnail', width: 480, quality: 78 },
  { key: 'mobile', width: 840, quality: 82 },
  { key: 'desktop', width: 1280, quality: 84 },
  { key: 'large', width: 1920, quality: 86 },
];

const labels = {
  Banio: 'Baño',
  Cocina: 'Cocina',
  Dorm: 'Dormitorio',
  Fachada: 'Fachada',
  Living: 'Sala de estar',
  Mesaliving: 'Sala de estar',
  Patio: 'Patio',
  Verde: 'Entorno verde',
  Verdedorm: 'Entorno verde',
  Verdeliving: 'Entorno verde',
};

const propertyId = (name) => (name === 'Casa La Arbolada' ? 'casa' : 'departamento');
const propertyLabel = (id) => (id === 'casa' ? 'Casa La Arbolada' : 'Departamento La Arbolada');
const slugify = (value) =>
  value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

function labelFor(file) {
  const base = labels[file.interpretedSpace] ?? file.interpretedSpace ?? 'Espacio';
  return file.interpretedSpaceNumber ? `${base} ${file.interpretedSpaceNumber}` : base;
}

function orientationFor(file) {
  return file.orientation === 'horizontal'
    ? 'landscape'
    : file.orientation === 'vertical'
      ? 'portrait'
      : 'square';
}

async function processFile(file) {
  const property = propertyId(file.interpretedProperty);
  const original = await fs.readFile(path.join(root, file.localPath));
  const decoded = await decodeHeic({ buffer: original });
  const source = Buffer.from(decoded.data.buffer, decoded.data.byteOffset, decoded.data.byteLength);
  const folder = path.join(outputRoot, property);
  const imageBase = slugify(path.parse(file.originalName).name);
  await fs.mkdir(folder, { recursive: true });

  const sources = {};
  for (const variant of variants) {
    if (variant.key === 'large' && decoded.width < 1600) continue;
    const outputName = `${imageBase}-${variant.key}.webp`;
    await sharp(source, { raw: { width: decoded.width, height: decoded.height, channels: 4 } })
      .rotate()
      .resize({ width: variant.width, withoutEnlargement: true, fit: 'inside' })
      .webp({ quality: variant.quality, smartSubsample: true })
      .toFile(path.join(folder, outputName));
    sources[variant.key] = `/images/${property}/${outputName}`;
  }

  return {
    id: `${property}-${imageBase}`,
    property,
    space: labelFor(file),
    spaceNumber: file.interpretedSpaceNumber,
    order: file.interpretedOrder ?? 0,
    originalName: file.originalName,
    width: decoded.width,
    height: decoded.height,
    orientation: orientationFor(file),
    alt: `${labelFor(file)} de ${propertyLabel(property)}.`,
    sources,
  };
}

function renderData(images) {
  return `// This file is generated by scripts/process-images.mjs. Do not edit manually.\n\nexport type PropertyImage = {\n  id: string;\n  property: 'casa' | 'departamento';\n  space: string;\n  spaceNumber: number | null;\n  order: number;\n  originalName: string;\n  width: number;\n  height: number;\n  orientation: 'landscape' | 'portrait' | 'square';\n  alt: string;\n  sources: { thumbnail: string; mobile: string; desktop: string; large?: string };\n  focalPoint?: { x: number; y: number };\n};\n\nexport const propertyImages: PropertyImage[] = ${JSON.stringify(images, null, 2)} as PropertyImage[];\n\nexport const casaImages = propertyImages.filter((image) => image.property === 'casa');\nexport const departamentoImages = propertyImages.filter((image) => image.property === 'departamento');\n`;
}

async function main() {
  const inventory = JSON.parse(await fs.readFile(inventoryPath, 'utf8'));
  const files = inventory.files.filter(
    (file) => file.width && file.height && file.interpretedProperty,
  );
  const images = [];
  for (let index = 0; index < files.length; index += 1) {
    const image = await processFile(files[index]);
    images.push(image);
    console.log(`[${index + 1}/${files.length}] ${image.originalName}`);
  }
  await fs.mkdir(path.dirname(dataPath), { recursive: true });
  await fs.writeFile(dataPath, renderData(images));
  console.log(`Procesadas ${images.length} imágenes WebP.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
