// This file is generated by scripts/process-images.mjs. Do not edit manually.

export type FocalPoint = {
  desktop: { x: number; y: number };
  mobile: { x: number; y: number };
};

export type PropertyImage = {
  id: string;
  property: 'casa' | 'departamento';
  space: string;
  spaceNumber: number | null;
  order: number;
  originalName: string;
  width: number;
  height: number;
  orientation: 'landscape' | 'portrait' | 'square';
  alt: string;
  sources: { thumbnail: string; mobile: string; desktop: string; large?: string };
  focalPoint?: FocalPoint;
};

export const propertyImages: PropertyImage[] = [
  {
    "id": "casa-exterior-hero",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "24728807-0FF5-4654-B3D7-4EC5DD7044B1.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Residencia principal de La Arbolada, con fachada de piedra, galería y parque.",
    "sources": {
      "thumbnail": "/images/casa/casa-exterior-hero-thumbnail.webp",
      "mobile": "/images/casa/casa-exterior-hero-mobile.webp",
      "desktop": "/images/casa/casa-exterior-hero-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 54,
        "y": 53
      },
      "mobile": {
        "x": 54,
        "y": 54
      }
    }
  },
  {
    "id": "casa-exterior-park",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "E7A9305B-D70F-4657-B667-0F28E82FAC4F.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Residencia principal vista desde el parque, con piedra, pérgola y arboleda.",
    "sources": {
      "thumbnail": "/images/casa/casa-exterior-park-thumbnail.webp",
      "mobile": "/images/casa/casa-exterior-park-mobile.webp",
      "desktop": "/images/casa/casa-exterior-park-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 50,
        "y": 52
      },
      "mobile": {
        "x": 50,
        "y": 51
      }
    }
  },
  {
    "id": "casa-arrival-bridge",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "030AEC37-735F-4CAB-9299-56E673E495E4.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Puente de piedra sobre el arroyo en el parque de La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/casa-arrival-bridge-thumbnail.webp",
      "mobile": "/images/casa/casa-arrival-bridge-mobile.webp",
      "desktop": "/images/casa/casa-arrival-bridge-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 54,
        "y": 56
      },
      "mobile": {
        "x": 56,
        "y": 56
      }
    }
  },
  {
    "id": "casa-arrival-entrance",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "B939E445-A10C-47B0-815B-4401DDAD55A0.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Entrada principal de La Arbolada, con piedra y puerta de madera.",
    "sources": {
      "thumbnail": "/images/casa/casa-arrival-entrance-thumbnail.webp",
      "mobile": "/images/casa/casa-arrival-entrance-mobile.webp",
      "desktop": "/images/casa/casa-arrival-entrance-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 50,
        "y": 50
      },
      "mobile": {
        "x": 50,
        "y": 50
      }
    }
  },
  {
    "id": "casa-living-wide",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "C0E4FF75-6E81-4D49-A028-CECF10661DC8.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Sala de estar y comedor de la residencia, con techo de madera y vistas al parque.",
    "sources": {
      "thumbnail": "/images/casa/casa-living-wide-thumbnail.webp",
      "mobile": "/images/casa/casa-living-wide-mobile.webp",
      "desktop": "/images/casa/casa-living-wide-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 51,
        "y": 50
      },
      "mobile": {
        "x": 52,
        "y": 49
      }
    }
  },
  {
    "id": "casa-living-dining",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "54C5D173-D947-479A-91BA-7CA61757B48F.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Comedor y sala de estar de La Arbolada, con vigas de madera.",
    "sources": {
      "thumbnail": "/images/casa/casa-living-dining-thumbnail.webp",
      "mobile": "/images/casa/casa-living-dining-mobile.webp",
      "desktop": "/images/casa/casa-living-dining-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 51,
        "y": 51
      },
      "mobile": {
        "x": 52,
        "y": 50
      }
    }
  },
  {
    "id": "casa-living-hearth",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "835AB9BF-A9FB-4630-B40A-87892ED8DD16.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Rincón de estar con hogar de piedra, madera y vista al parque.",
    "sources": {
      "thumbnail": "/images/casa/casa-living-hearth-thumbnail.webp",
      "mobile": "/images/casa/casa-living-hearth-mobile.webp",
      "desktop": "/images/casa/casa-living-hearth-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 50,
        "y": 52
      },
      "mobile": {
        "x": 51,
        "y": 52
      }
    }
  },
  {
    "id": "casa-kitchen-island",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "02568D04-2853-49B0-B438-D49E00D1299F.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Cocina con isla, techo de madera y barra desayunadora.",
    "sources": {
      "thumbnail": "/images/casa/casa-kitchen-island-thumbnail.webp",
      "mobile": "/images/casa/casa-kitchen-island-mobile.webp",
      "desktop": "/images/casa/casa-kitchen-island-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 51,
        "y": 52
      },
      "mobile": {
        "x": 52,
        "y": 52
      }
    }
  },
  {
    "id": "casa-kitchen-detail",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "D8444BE8-B225-46A9-991A-BF4242F533B3.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Cocina equipada de La Arbolada con barra de madera y vista al verde.",
    "sources": {
      "thumbnail": "/images/casa/casa-kitchen-detail-thumbnail.webp",
      "mobile": "/images/casa/casa-kitchen-detail-mobile.webp",
      "desktop": "/images/casa/casa-kitchen-detail-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 50,
        "y": 52
      },
      "mobile": {
        "x": 51,
        "y": 52
      }
    }
  },
  {
    "id": "casa-kitchen-dining",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "DDA96AC8-0A99-4A26-A231-A3EDF3EB4F44.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Cocina y comedor diario de la residencia principal.",
    "sources": {
      "thumbnail": "/images/casa/casa-kitchen-dining-thumbnail.webp",
      "mobile": "/images/casa/casa-kitchen-dining-mobile.webp",
      "desktop": "/images/casa/casa-kitchen-dining-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 50,
        "y": 51
      },
      "mobile": {
        "x": 50,
        "y": 51
      }
    }
  },
  {
    "id": "casa-bedroom-main",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "137C2916-229F-4CCB-968D-F8F697D5E3B7.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Dormitorio principal con techo de madera y ventana hacia el parque.",
    "sources": {
      "thumbnail": "/images/casa/casa-bedroom-main-thumbnail.webp",
      "mobile": "/images/casa/casa-bedroom-main-mobile.webp",
      "desktop": "/images/casa/casa-bedroom-main-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 51,
        "y": 52
      },
      "mobile": {
        "x": 52,
        "y": 52
      }
    }
  },
  {
    "id": "casa-bedroom-twin",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "66BA1958-E26E-44E6-8BC7-90409F82B338.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Dormitorio con camas individuales de la residencia principal.",
    "sources": {
      "thumbnail": "/images/casa/casa-bedroom-twin-thumbnail.webp",
      "mobile": "/images/casa/casa-bedroom-twin-mobile.webp",
      "desktop": "/images/casa/casa-bedroom-twin-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 51,
        "y": 52
      },
      "mobile": {
        "x": 51,
        "y": 52
      }
    }
  },
  {
    "id": "casa-bedroom-garden",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "EE0CCB4A-ADD9-4CAB-9F94-640B4F0BAEF4.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Dormitorio de la residencia con salida hacia la terraza y el parque.",
    "sources": {
      "thumbnail": "/images/casa/casa-bedroom-garden-thumbnail.webp",
      "mobile": "/images/casa/casa-bedroom-garden-mobile.webp",
      "desktop": "/images/casa/casa-bedroom-garden-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 51,
        "y": 51
      },
      "mobile": {
        "x": 51,
        "y": 51
      }
    }
  },
  {
    "id": "casa-bedroom-terrace",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "C6A83CA2-A4C1-4853-A2A0-5A0A1EE889DC.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Dormitorio luminoso con techo de madera y acceso a la terraza.",
    "sources": {
      "thumbnail": "/images/casa/casa-bedroom-terrace-thumbnail.webp",
      "mobile": "/images/casa/casa-bedroom-terrace-mobile.webp",
      "desktop": "/images/casa/casa-bedroom-terrace-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 51,
        "y": 52
      },
      "mobile": {
        "x": 52,
        "y": 52
      }
    }
  },
  {
    "id": "casa-bath-main",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "10DD31C7-96A6-46BC-A96C-790536CEC5FD.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Baño de la residencia principal con terminaciones de piedra y madera.",
    "sources": {
      "thumbnail": "/images/casa/casa-bath-main-thumbnail.webp",
      "mobile": "/images/casa/casa-bath-main-mobile.webp",
      "desktop": "/images/casa/casa-bath-main-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 50,
        "y": 52
      },
      "mobile": {
        "x": 50,
        "y": 52
      }
    }
  },
  {
    "id": "casa-bath-secondary",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "F9FB49C6-6FD3-4365-81C5-399C9DEC620E.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Baño secundario de la residencia principal.",
    "sources": {
      "thumbnail": "/images/casa/casa-bath-secondary-thumbnail.webp",
      "mobile": "/images/casa/casa-bath-secondary-mobile.webp",
      "desktop": "/images/casa/casa-bath-secondary-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 50,
        "y": 52
      },
      "mobile": {
        "x": 50,
        "y": 52
      }
    }
  },
  {
    "id": "casa-patio-sunset",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "50091321-D799-4443-AF00-8C6933F461FF.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Jardín de piedra al atardecer junto a la residencia principal.",
    "sources": {
      "thumbnail": "/images/casa/casa-patio-sunset-thumbnail.webp",
      "mobile": "/images/casa/casa-patio-sunset-mobile.webp",
      "desktop": "/images/casa/casa-patio-sunset-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 50,
        "y": 53
      },
      "mobile": {
        "x": 50,
        "y": 53
      }
    }
  },
  {
    "id": "casa-park-stone",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "08CB1FE0-3DDE-402F-8E07-D92212DABEBC.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Parque de La Arbolada al atardecer, con senderos y muros de piedra.",
    "sources": {
      "thumbnail": "/images/casa/casa-park-stone-thumbnail.webp",
      "mobile": "/images/casa/casa-park-stone-mobile.webp",
      "desktop": "/images/casa/casa-park-stone-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 50,
        "y": 52
      },
      "mobile": {
        "x": 50,
        "y": 52
      }
    }
  },
  {
    "id": "casa-creek",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "1F6E207F-24B3-4B09-8039-41329F0E93F5.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Arroyo y puente entre los árboles del parque de La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/casa-creek-thumbnail.webp",
      "mobile": "/images/casa/casa-creek-mobile.webp",
      "desktop": "/images/casa/casa-creek-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 52,
        "y": 54
      },
      "mobile": {
        "x": 54,
        "y": 54
      }
    }
  },
  {
    "id": "casa-park-willow",
    "property": "casa",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "CD085BBB-3A17-4A6B-8705-13AF0C7E3588.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Sauces y parque arbolado de La Arbolada al atardecer.",
    "sources": {
      "thumbnail": "/images/casa/casa-park-willow-thumbnail.webp",
      "mobile": "/images/casa/casa-park-willow-mobile.webp",
      "desktop": "/images/casa/casa-park-willow-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 52,
        "y": 52
      },
      "mobile": {
        "x": 52,
        "y": 52
      }
    }
  },
  {
    "id": "departamento-exterior-hero",
    "property": "departamento",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "124784A0-36E3-47F5-A7EE-49F554E1AC18.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Fachada de piedra y acceso del departamento independiente de La Arbolada.",
    "sources": {
      "thumbnail": "/images/departamento/departamento-exterior-hero-thumbnail.webp",
      "mobile": "/images/departamento/departamento-exterior-hero-mobile.webp",
      "desktop": "/images/departamento/departamento-exterior-hero-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 50,
        "y": 52
      },
      "mobile": {
        "x": 51,
        "y": 52
      }
    }
  },
  {
    "id": "departamento-exterior-wide",
    "property": "departamento",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "43C288E5-C509-48C1-B7E8-34D2CBDC27C2.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Exterior y acceso lateral del departamento independiente, integrado al parque.",
    "sources": {
      "thumbnail": "/images/departamento/departamento-exterior-wide-thumbnail.webp",
      "mobile": "/images/departamento/departamento-exterior-wide-mobile.webp",
      "desktop": "/images/departamento/departamento-exterior-wide-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 55,
        "y": 52
      },
      "mobile": {
        "x": 56,
        "y": 52
      }
    }
  },
  {
    "id": "departamento-living-wide",
    "property": "departamento",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "CD0ADB2D-1FB3-4FAC-8DF1-2E357921DF7E.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Sala de estar y comedor del departamento independiente.",
    "sources": {
      "thumbnail": "/images/departamento/departamento-living-wide-thumbnail.webp",
      "mobile": "/images/departamento/departamento-living-wide-mobile.webp",
      "desktop": "/images/departamento/departamento-living-wide-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 51,
        "y": 52
      },
      "mobile": {
        "x": 51,
        "y": 52
      }
    }
  },
  {
    "id": "departamento-dining",
    "property": "departamento",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "8C33E584-859B-4EB1-8596-F10276E5203A.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Comedor del departamento independiente de La Arbolada.",
    "sources": {
      "thumbnail": "/images/departamento/departamento-dining-thumbnail.webp",
      "mobile": "/images/departamento/departamento-dining-mobile.webp",
      "desktop": "/images/departamento/departamento-dining-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 52,
        "y": 52
      },
      "mobile": {
        "x": 52,
        "y": 52
      }
    }
  },
  {
    "id": "departamento-kitchen",
    "property": "departamento",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "92F79282-2309-4D65-AE8F-6F2D72397181.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Cocina equipada del departamento independiente.",
    "sources": {
      "thumbnail": "/images/departamento/departamento-kitchen-thumbnail.webp",
      "mobile": "/images/departamento/departamento-kitchen-mobile.webp",
      "desktop": "/images/departamento/departamento-kitchen-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 50,
        "y": 52
      },
      "mobile": {
        "x": 50,
        "y": 52
      }
    }
  },
  {
    "id": "departamento-bedroom-main",
    "property": "departamento",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "42DCF1DD-AF01-4FFC-A437-3316906EA655.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Dormitorio del departamento independiente con placard integrado.",
    "sources": {
      "thumbnail": "/images/departamento/departamento-bedroom-main-thumbnail.webp",
      "mobile": "/images/departamento/departamento-bedroom-main-mobile.webp",
      "desktop": "/images/departamento/departamento-bedroom-main-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 51,
        "y": 52
      },
      "mobile": {
        "x": 52,
        "y": 52
      }
    }
  },
  {
    "id": "departamento-bedroom-twin",
    "property": "departamento",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "BAA7B0AF-8E71-448D-9C11-354CB1DD5E12.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Dormitorio con camas individuales y vista al verde del departamento.",
    "sources": {
      "thumbnail": "/images/departamento/departamento-bedroom-twin-thumbnail.webp",
      "mobile": "/images/departamento/departamento-bedroom-twin-mobile.webp",
      "desktop": "/images/departamento/departamento-bedroom-twin-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 51,
        "y": 52
      },
      "mobile": {
        "x": 52,
        "y": 52
      }
    }
  },
  {
    "id": "departamento-bath-wide",
    "property": "departamento",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "5333EF57-25E3-48BC-8651-9E8D89215BB7.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Baño completo del departamento independiente.",
    "sources": {
      "thumbnail": "/images/departamento/departamento-bath-wide-thumbnail.webp",
      "mobile": "/images/departamento/departamento-bath-wide-mobile.webp",
      "desktop": "/images/departamento/departamento-bath-wide-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 50,
        "y": 52
      },
      "mobile": {
        "x": 50,
        "y": 52
      }
    }
  },
  {
    "id": "departamento-bath-detail",
    "property": "departamento",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "07A7C837-1226-4DAC-9D94-E94CF1B84C6E.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Detalle del baño con ducha del departamento independiente.",
    "sources": {
      "thumbnail": "/images/departamento/departamento-bath-detail-thumbnail.webp",
      "mobile": "/images/departamento/departamento-bath-detail-mobile.webp",
      "desktop": "/images/departamento/departamento-bath-detail-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 50,
        "y": 52
      },
      "mobile": {
        "x": 50,
        "y": 52
      }
    }
  },
  {
    "id": "departamento-wood-oven",
    "property": "departamento",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "A8C61A30-CBE2-44EE-8AC3-C719D75B5896.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Horno de barro de piedra en el parque compartido de La Arbolada.",
    "sources": {
      "thumbnail": "/images/departamento/departamento-wood-oven-thumbnail.webp",
      "mobile": "/images/departamento/departamento-wood-oven-mobile.webp",
      "desktop": "/images/departamento/departamento-wood-oven-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 50,
        "y": 52
      },
      "mobile": {
        "x": 50,
        "y": 52
      }
    }
  },
  {
    "id": "departamento-pergola",
    "property": "departamento",
    "space": "Fotografía curada",
    "spaceNumber": null,
    "order": 0,
    "originalName": "ABF1F507-6246-426F-9FD1-58F2B0CE9FD3.PNG",
    "width": 1448,
    "height": 1086,
    "orientation": "landscape",
    "alt": "Pérgola y parque compartido de La Arbolada.",
    "sources": {
      "thumbnail": "/images/departamento/departamento-pergola-thumbnail.webp",
      "mobile": "/images/departamento/departamento-pergola-mobile.webp",
      "desktop": "/images/departamento/departamento-pergola-desktop.webp"
    },
    "focalPoint": {
      "desktop": {
        "x": 50,
        "y": 52
      },
      "mobile": {
        "x": 50,
        "y": 52
      }
    }
  }
] as PropertyImage[];

export const casaImages = propertyImages.filter((image) => image.property === 'casa');
export const departamentoImages = propertyImages.filter((image) => image.property === 'departamento');
