// This file is generated by scripts/process-images.mjs. Do not edit manually.

export type PropertyImage = {
  id: string;
  property: 'casa' | 'departamento';
  space: string;
  spaceNumber: number | null;
  order: number;
  originalName: string;
  width: number;
  height: number;
  orientation: 'landscape' | 'portrait' | 'square';
  alt: string;
  sources: { thumbnail: string; mobile: string; desktop: string; large?: string };
  focalPoint?: { x: number; y: number };
};

export const propertyImages: PropertyImage[] = [
  {
    "id": "casa-5casa",
    "property": "casa",
    "space": "Espacio 5",
    "spaceNumber": 5,
    "order": 0,
    "originalName": "5CASA.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Espacio 5 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/5casa-thumbnail.webp",
      "mobile": "/images/casa/5casa-mobile.webp",
      "desktop": "/images/casa/5casa-desktop.webp",
      "large": "/images/casa/5casa-large.webp"
    }
  },
  {
    "id": "casa-banio1casa1",
    "property": "casa",
    "space": "Baño 1",
    "spaceNumber": 1,
    "order": 1,
    "originalName": "banio1CASA1.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Baño 1 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/banio1casa1-thumbnail.webp",
      "mobile": "/images/casa/banio1casa1-mobile.webp",
      "desktop": "/images/casa/banio1casa1-desktop.webp",
      "large": "/images/casa/banio1casa1-large.webp"
    }
  },
  {
    "id": "casa-banio1casa2",
    "property": "casa",
    "space": "Baño 1",
    "spaceNumber": 1,
    "order": 2,
    "originalName": "banio1CASA2.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Baño 1 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/banio1casa2-thumbnail.webp",
      "mobile": "/images/casa/banio1casa2-mobile.webp",
      "desktop": "/images/casa/banio1casa2-desktop.webp",
      "large": "/images/casa/banio1casa2-large.webp"
    }
  },
  {
    "id": "casa-banio1casa3",
    "property": "casa",
    "space": "Baño 1",
    "spaceNumber": 1,
    "order": 3,
    "originalName": "banio1CASA3.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Baño 1 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/banio1casa3-thumbnail.webp",
      "mobile": "/images/casa/banio1casa3-mobile.webp",
      "desktop": "/images/casa/banio1casa3-desktop.webp",
      "large": "/images/casa/banio1casa3-large.webp"
    }
  },
  {
    "id": "casa-banio2casa1",
    "property": "casa",
    "space": "Baño 2",
    "spaceNumber": 2,
    "order": 1,
    "originalName": "banio2CASA1.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Baño 2 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/banio2casa1-thumbnail.webp",
      "mobile": "/images/casa/banio2casa1-mobile.webp",
      "desktop": "/images/casa/banio2casa1-desktop.webp",
      "large": "/images/casa/banio2casa1-large.webp"
    }
  },
  {
    "id": "casa-banio2casa2",
    "property": "casa",
    "space": "Baño 2",
    "spaceNumber": 2,
    "order": 2,
    "originalName": "banio2CASA2.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Baño 2 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/banio2casa2-thumbnail.webp",
      "mobile": "/images/casa/banio2casa2-mobile.webp",
      "desktop": "/images/casa/banio2casa2-desktop.webp",
      "large": "/images/casa/banio2casa2-large.webp"
    }
  },
  {
    "id": "casa-banio2casa3",
    "property": "casa",
    "space": "Baño 2",
    "spaceNumber": 2,
    "order": 3,
    "originalName": "banio2CASA3.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Baño 2 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/banio2casa3-thumbnail.webp",
      "mobile": "/images/casa/banio2casa3-mobile.webp",
      "desktop": "/images/casa/banio2casa3-desktop.webp",
      "large": "/images/casa/banio2casa3-large.webp"
    }
  },
  {
    "id": "casa-cocinacasa1",
    "property": "casa",
    "space": "Cocina",
    "spaceNumber": null,
    "order": 1,
    "originalName": "cocinaCASA1.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Cocina de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/cocinacasa1-thumbnail.webp",
      "mobile": "/images/casa/cocinacasa1-mobile.webp",
      "desktop": "/images/casa/cocinacasa1-desktop.webp",
      "large": "/images/casa/cocinacasa1-large.webp"
    }
  },
  {
    "id": "casa-cocinacasa2",
    "property": "casa",
    "space": "Cocina",
    "spaceNumber": null,
    "order": 2,
    "originalName": "cocinaCASA2.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Cocina de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/cocinacasa2-thumbnail.webp",
      "mobile": "/images/casa/cocinacasa2-mobile.webp",
      "desktop": "/images/casa/cocinacasa2-desktop.webp",
      "large": "/images/casa/cocinacasa2-large.webp"
    }
  },
  {
    "id": "casa-cocinacasa3",
    "property": "casa",
    "space": "Cocina",
    "spaceNumber": null,
    "order": 3,
    "originalName": "cocinaCASA3.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Cocina de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/cocinacasa3-thumbnail.webp",
      "mobile": "/images/casa/cocinacasa3-mobile.webp",
      "desktop": "/images/casa/cocinacasa3-desktop.webp",
      "large": "/images/casa/cocinacasa3-large.webp"
    }
  },
  {
    "id": "casa-cocinacasa4",
    "property": "casa",
    "space": "Cocina",
    "spaceNumber": null,
    "order": 4,
    "originalName": "cocinaCASA4.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Cocina de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/cocinacasa4-thumbnail.webp",
      "mobile": "/images/casa/cocinacasa4-mobile.webp",
      "desktop": "/images/casa/cocinacasa4-desktop.webp",
      "large": "/images/casa/cocinacasa4-large.webp"
    }
  },
  {
    "id": "casa-cocinacasa5",
    "property": "casa",
    "space": "Cocina",
    "spaceNumber": null,
    "order": 5,
    "originalName": "cocinaCASA5.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Cocina de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/cocinacasa5-thumbnail.webp",
      "mobile": "/images/casa/cocinacasa5-mobile.webp",
      "desktop": "/images/casa/cocinacasa5-desktop.webp",
      "large": "/images/casa/cocinacasa5-large.webp"
    }
  },
  {
    "id": "casa-dorm1casa1",
    "property": "casa",
    "space": "Dormitorio 1",
    "spaceNumber": 1,
    "order": 1,
    "originalName": "dorm1CASA1.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Dormitorio 1 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/dorm1casa1-thumbnail.webp",
      "mobile": "/images/casa/dorm1casa1-mobile.webp",
      "desktop": "/images/casa/dorm1casa1-desktop.webp",
      "large": "/images/casa/dorm1casa1-large.webp"
    }
  },
  {
    "id": "casa-dorm1casa2",
    "property": "casa",
    "space": "Dormitorio 1",
    "spaceNumber": 1,
    "order": 2,
    "originalName": "dorm1CASA2.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Dormitorio 1 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/dorm1casa2-thumbnail.webp",
      "mobile": "/images/casa/dorm1casa2-mobile.webp",
      "desktop": "/images/casa/dorm1casa2-desktop.webp",
      "large": "/images/casa/dorm1casa2-large.webp"
    }
  },
  {
    "id": "casa-dorm1casa3",
    "property": "casa",
    "space": "Dormitorio 1",
    "spaceNumber": 1,
    "order": 3,
    "originalName": "dorm1CASA3.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Dormitorio 1 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/dorm1casa3-thumbnail.webp",
      "mobile": "/images/casa/dorm1casa3-mobile.webp",
      "desktop": "/images/casa/dorm1casa3-desktop.webp",
      "large": "/images/casa/dorm1casa3-large.webp"
    }
  },
  {
    "id": "casa-dorm1casa5",
    "property": "casa",
    "space": "Dormitorio 1",
    "spaceNumber": 1,
    "order": 5,
    "originalName": "dorm1CASA5.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Dormitorio 1 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/dorm1casa5-thumbnail.webp",
      "mobile": "/images/casa/dorm1casa5-mobile.webp",
      "desktop": "/images/casa/dorm1casa5-desktop.webp",
      "large": "/images/casa/dorm1casa5-large.webp"
    }
  },
  {
    "id": "casa-dorm2casa1",
    "property": "casa",
    "space": "Dormitorio 2",
    "spaceNumber": 2,
    "order": 1,
    "originalName": "dorm2CASA1.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Dormitorio 2 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/dorm2casa1-thumbnail.webp",
      "mobile": "/images/casa/dorm2casa1-mobile.webp",
      "desktop": "/images/casa/dorm2casa1-desktop.webp",
      "large": "/images/casa/dorm2casa1-large.webp"
    }
  },
  {
    "id": "casa-dorm2casa2",
    "property": "casa",
    "space": "Dormitorio 2",
    "spaceNumber": 2,
    "order": 2,
    "originalName": "dorm2CASA2.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Dormitorio 2 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/dorm2casa2-thumbnail.webp",
      "mobile": "/images/casa/dorm2casa2-mobile.webp",
      "desktop": "/images/casa/dorm2casa2-desktop.webp",
      "large": "/images/casa/dorm2casa2-large.webp"
    }
  },
  {
    "id": "casa-dorm2casa3",
    "property": "casa",
    "space": "Dormitorio 2",
    "spaceNumber": 2,
    "order": 3,
    "originalName": "dorm2CASA3.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Dormitorio 2 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/dorm2casa3-thumbnail.webp",
      "mobile": "/images/casa/dorm2casa3-mobile.webp",
      "desktop": "/images/casa/dorm2casa3-desktop.webp",
      "large": "/images/casa/dorm2casa3-large.webp"
    }
  },
  {
    "id": "casa-dorm3casa1",
    "property": "casa",
    "space": "Dormitorio 3",
    "spaceNumber": 3,
    "order": 1,
    "originalName": "dorm3CASA1.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Dormitorio 3 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/dorm3casa1-thumbnail.webp",
      "mobile": "/images/casa/dorm3casa1-mobile.webp",
      "desktop": "/images/casa/dorm3casa1-desktop.webp",
      "large": "/images/casa/dorm3casa1-large.webp"
    }
  },
  {
    "id": "casa-dorm3casa2",
    "property": "casa",
    "space": "Dormitorio 3",
    "spaceNumber": 3,
    "order": 2,
    "originalName": "dorm3CASA2.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Dormitorio 3 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/dorm3casa2-thumbnail.webp",
      "mobile": "/images/casa/dorm3casa2-mobile.webp",
      "desktop": "/images/casa/dorm3casa2-desktop.webp",
      "large": "/images/casa/dorm3casa2-large.webp"
    }
  },
  {
    "id": "casa-dorm4casa1",
    "property": "casa",
    "space": "Dormitorio 4",
    "spaceNumber": 4,
    "order": 1,
    "originalName": "dorm4CASA1.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Dormitorio 4 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/dorm4casa1-thumbnail.webp",
      "mobile": "/images/casa/dorm4casa1-mobile.webp",
      "desktop": "/images/casa/dorm4casa1-desktop.webp",
      "large": "/images/casa/dorm4casa1-large.webp"
    }
  },
  {
    "id": "casa-dorm4casa2",
    "property": "casa",
    "space": "Dormitorio 4",
    "spaceNumber": 4,
    "order": 2,
    "originalName": "dorm4CASA2.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Dormitorio 4 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/dorm4casa2-thumbnail.webp",
      "mobile": "/images/casa/dorm4casa2-mobile.webp",
      "desktop": "/images/casa/dorm4casa2-desktop.webp",
      "large": "/images/casa/dorm4casa2-large.webp"
    }
  },
  {
    "id": "casa-fachada1",
    "property": "casa",
    "space": "Fachada",
    "spaceNumber": null,
    "order": 1,
    "originalName": "fachada1.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Fachada de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/fachada1-thumbnail.webp",
      "mobile": "/images/casa/fachada1-mobile.webp",
      "desktop": "/images/casa/fachada1-desktop.webp",
      "large": "/images/casa/fachada1-large.webp"
    }
  },
  {
    "id": "casa-fachada2",
    "property": "casa",
    "space": "Fachada",
    "spaceNumber": null,
    "order": 2,
    "originalName": "fachada2.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Fachada de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/fachada2-thumbnail.webp",
      "mobile": "/images/casa/fachada2-mobile.webp",
      "desktop": "/images/casa/fachada2-desktop.webp",
      "large": "/images/casa/fachada2-large.webp"
    }
  },
  {
    "id": "casa-fachada3",
    "property": "casa",
    "space": "Fachada",
    "spaceNumber": null,
    "order": 3,
    "originalName": "fachada3.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Fachada de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/fachada3-thumbnail.webp",
      "mobile": "/images/casa/fachada3-mobile.webp",
      "desktop": "/images/casa/fachada3-desktop.webp",
      "large": "/images/casa/fachada3-large.webp"
    }
  },
  {
    "id": "casa-fachada4",
    "property": "casa",
    "space": "Fachada",
    "spaceNumber": null,
    "order": 4,
    "originalName": "fachada4.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Fachada de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/fachada4-thumbnail.webp",
      "mobile": "/images/casa/fachada4-mobile.webp",
      "desktop": "/images/casa/fachada4-desktop.webp",
      "large": "/images/casa/fachada4-large.webp"
    }
  },
  {
    "id": "casa-livingcasa3",
    "property": "casa",
    "space": "Living",
    "spaceNumber": null,
    "order": 3,
    "originalName": "livingCASA3.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Living de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/nuevas/living/living-2-thumbnail.webp",
      "mobile": "/images/nuevas/living/living-2-mobile.webp",
      "desktop": "/images/nuevas/living/living-2-desktop.webp",
      "large": "/images/nuevas/living/living-2-large.webp"
    }
  },
  {
    "id": "casa-livingcasa",
    "property": "casa",
    "space": "Living",
    "spaceNumber": null,
    "order": 0,
    "originalName": "livingCASA.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Living de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/nuevas/living/living-1-thumbnail.webp",
      "mobile": "/images/nuevas/living/living-1-mobile.webp",
      "desktop": "/images/nuevas/living/living-1-desktop.webp",
      "large": "/images/nuevas/living/living-1-large.webp"
    }
  },
  {
    "id": "casa-mesalivingcasa4",
    "property": "casa",
    "space": "Living",
    "spaceNumber": null,
    "order": 4,
    "originalName": "mesaLIVINGCASA4.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Living de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/nuevas/living/living-3-thumbnail.webp",
      "mobile": "/images/nuevas/living/living-3-mobile.webp",
      "desktop": "/images/nuevas/living/living-3-desktop.webp",
      "large": "/images/nuevas/living/living-3-large.webp"
    }
  },
  {
    "id": "casa-patio1",
    "property": "casa",
    "space": "Patio",
    "spaceNumber": null,
    "order": 1,
    "originalName": "patio1.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Patio de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/patio1-thumbnail.webp",
      "mobile": "/images/casa/patio1-mobile.webp",
      "desktop": "/images/casa/patio1-desktop.webp",
      "large": "/images/casa/patio1-large.webp"
    }
  },
  {
    "id": "casa-patio2",
    "property": "casa",
    "space": "Patio",
    "spaceNumber": null,
    "order": 2,
    "originalName": "patio2.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Patio de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/patio2-thumbnail.webp",
      "mobile": "/images/casa/patio2-mobile.webp",
      "desktop": "/images/casa/patio2-desktop.webp",
      "large": "/images/casa/patio2-large.webp"
    }
  },
  {
    "id": "casa-patio3",
    "property": "casa",
    "space": "Patio",
    "spaceNumber": null,
    "order": 3,
    "originalName": "patio3.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Patio de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/patio3-thumbnail.webp",
      "mobile": "/images/casa/patio3-mobile.webp",
      "desktop": "/images/casa/patio3-desktop.webp",
      "large": "/images/casa/patio3-large.webp"
    }
  },
  {
    "id": "casa-patio4",
    "property": "casa",
    "space": "Patio",
    "spaceNumber": null,
    "order": 4,
    "originalName": "patio4.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Patio de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/patio4-thumbnail.webp",
      "mobile": "/images/casa/patio4-mobile.webp",
      "desktop": "/images/casa/patio4-desktop.webp",
      "large": "/images/casa/patio4-large.webp"
    }
  },
  {
    "id": "casa-patio5",
    "property": "casa",
    "space": "Patio",
    "spaceNumber": null,
    "order": 5,
    "originalName": "patio5.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Patio de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/patio5-thumbnail.webp",
      "mobile": "/images/casa/patio5-mobile.webp",
      "desktop": "/images/casa/patio5-desktop.webp",
      "large": "/images/casa/patio5-large.webp"
    }
  },
  {
    "id": "casa-patio6",
    "property": "casa",
    "space": "Patio",
    "spaceNumber": null,
    "order": 6,
    "originalName": "patio6.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Patio de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/patio6-thumbnail.webp",
      "mobile": "/images/casa/patio6-mobile.webp",
      "desktop": "/images/casa/patio6-desktop.webp",
      "large": "/images/casa/patio6-large.webp"
    }
  },
  {
    "id": "casa-patio7",
    "property": "casa",
    "space": "Patio",
    "spaceNumber": null,
    "order": 7,
    "originalName": "patio7.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Patio de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/patio7-thumbnail.webp",
      "mobile": "/images/casa/patio7-mobile.webp",
      "desktop": "/images/casa/patio7-desktop.webp",
      "large": "/images/casa/patio7-large.webp"
    }
  },
  {
    "id": "casa-patio8",
    "property": "casa",
    "space": "Patio",
    "spaceNumber": null,
    "order": 8,
    "originalName": "patio8.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Patio de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/patio8-thumbnail.webp",
      "mobile": "/images/casa/patio8-mobile.webp",
      "desktop": "/images/casa/patio8-desktop.webp",
      "large": "/images/casa/patio8-large.webp"
    }
  },
  {
    "id": "casa-patio9",
    "property": "casa",
    "space": "Patio",
    "spaceNumber": null,
    "order": 9,
    "originalName": "patio9.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Patio de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/patio9-thumbnail.webp",
      "mobile": "/images/casa/patio9-mobile.webp",
      "desktop": "/images/casa/patio9-desktop.webp",
      "large": "/images/casa/patio9-large.webp"
    }
  },
  {
    "id": "casa-patio10",
    "property": "casa",
    "space": "Patio",
    "spaceNumber": null,
    "order": 10,
    "originalName": "patio10.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Patio de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/patio10-thumbnail.webp",
      "mobile": "/images/casa/patio10-mobile.webp",
      "desktop": "/images/casa/patio10-desktop.webp",
      "large": "/images/casa/patio10-large.webp"
    }
  },
  {
    "id": "casa-patio11",
    "property": "casa",
    "space": "Patio",
    "spaceNumber": null,
    "order": 11,
    "originalName": "patio11.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Patio de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/patio11-thumbnail.webp",
      "mobile": "/images/casa/patio11-mobile.webp",
      "desktop": "/images/casa/patio11-desktop.webp",
      "large": "/images/casa/patio11-large.webp"
    }
  },
  {
    "id": "casa-verdedorm1casa",
    "property": "casa",
    "space": "Entorno verde 1",
    "spaceNumber": 1,
    "order": 0,
    "originalName": "verdeDorm1CASA.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Entorno verde 1 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/verdedorm1casa-thumbnail.webp",
      "mobile": "/images/casa/verdedorm1casa-mobile.webp",
      "desktop": "/images/casa/verdedorm1casa-desktop.webp",
      "large": "/images/casa/verdedorm1casa-large.webp"
    }
  },
  {
    "id": "casa-verdedorm2casa",
    "property": "casa",
    "space": "Entorno verde 2",
    "spaceNumber": 2,
    "order": 0,
    "originalName": "verdeDorm2CASA.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Entorno verde 2 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/verdedorm2casa-thumbnail.webp",
      "mobile": "/images/casa/verdedorm2casa-mobile.webp",
      "desktop": "/images/casa/verdedorm2casa-desktop.webp",
      "large": "/images/casa/verdedorm2casa-large.webp"
    }
  },
  {
    "id": "casa-verdedorm3casa",
    "property": "casa",
    "space": "Entorno verde 3",
    "spaceNumber": 3,
    "order": 0,
    "originalName": "verdeDorm3CASA.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Entorno verde 3 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/verdedorm3casa-thumbnail.webp",
      "mobile": "/images/casa/verdedorm3casa-mobile.webp",
      "desktop": "/images/casa/verdedorm3casa-desktop.webp",
      "large": "/images/casa/verdedorm3casa-large.webp"
    }
  },
  {
    "id": "casa-verdeliving1casa",
    "property": "casa",
    "space": "Entorno verde 1",
    "spaceNumber": 1,
    "order": 0,
    "originalName": "verdeLIVING1CASA.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Entorno verde 1 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/verdeliving1casa-thumbnail.webp",
      "mobile": "/images/casa/verdeliving1casa-mobile.webp",
      "desktop": "/images/casa/verdeliving1casa-desktop.webp",
      "large": "/images/casa/verdeliving1casa-large.webp"
    }
  },
  {
    "id": "casa-verdeliving2casa",
    "property": "casa",
    "space": "Entorno verde 2",
    "spaceNumber": 2,
    "order": 0,
    "originalName": "verdeLIVING2CASA.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Entorno verde 2 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/verdeliving2casa-thumbnail.webp",
      "mobile": "/images/casa/verdeliving2casa-mobile.webp",
      "desktop": "/images/casa/verdeliving2casa-desktop.webp",
      "large": "/images/casa/verdeliving2casa-large.webp"
    }
  },
  {
    "id": "casa-verdeliving3casa",
    "property": "casa",
    "space": "Entorno verde 3",
    "spaceNumber": 3,
    "order": 0,
    "originalName": "verdeLIVING3CASA.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Entorno verde 3 de Casa La Arbolada.",
    "sources": {
      "thumbnail": "/images/casa/verdeliving3casa-thumbnail.webp",
      "mobile": "/images/casa/verdeliving3casa-mobile.webp",
      "desktop": "/images/casa/verdeliving3casa-desktop.webp",
      "large": "/images/casa/verdeliving3casa-large.webp"
    }
  },
  {
    "id": "departamento-banio1dpto",
    "property": "departamento",
    "space": "Baño 1",
    "spaceNumber": 1,
    "order": 0,
    "originalName": "banio1DPTO.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Baño 1 de Departamento La Arbolada.",
    "sources": {
      "thumbnail": "/images/departamento/banio1dpto-thumbnail.webp",
      "mobile": "/images/departamento/banio1dpto-mobile.webp",
      "desktop": "/images/departamento/banio1dpto-desktop.webp",
      "large": "/images/departamento/banio1dpto-large.webp"
    }
  },
  {
    "id": "departamento-baniodpto2",
    "property": "departamento",
    "space": "Baño",
    "spaceNumber": null,
    "order": 2,
    "originalName": "banioDPTO2.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Baño de Departamento La Arbolada.",
    "sources": {
      "thumbnail": "/images/departamento/baniodpto2-thumbnail.webp",
      "mobile": "/images/departamento/baniodpto2-mobile.webp",
      "desktop": "/images/departamento/baniodpto2-desktop.webp",
      "large": "/images/departamento/baniodpto2-large.webp"
    }
  },
  {
    "id": "departamento-cocinadpto1",
    "property": "departamento",
    "space": "Cocina",
    "spaceNumber": null,
    "order": 1,
    "originalName": "CocinaDPTO1.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Cocina de Departamento La Arbolada.",
    "sources": {
      "thumbnail": "/images/departamento/cocinadpto1-thumbnail.webp",
      "mobile": "/images/departamento/cocinadpto1-mobile.webp",
      "desktop": "/images/departamento/cocinadpto1-desktop.webp",
      "large": "/images/departamento/cocinadpto1-large.webp"
    }
  },
  {
    "id": "departamento-dormdpto1",
    "property": "departamento",
    "space": "Dormitorio",
    "spaceNumber": null,
    "order": 1,
    "originalName": "dormDPTO1.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Dormitorio de Departamento La Arbolada.",
    "sources": {
      "thumbnail": "/images/departamento/dormdpto1-thumbnail.webp",
      "mobile": "/images/departamento/dormdpto1-mobile.webp",
      "desktop": "/images/departamento/dormdpto1-desktop.webp",
      "large": "/images/departamento/dormdpto1-large.webp"
    }
  },
  {
    "id": "departamento-dormdpto2",
    "property": "departamento",
    "space": "Dormitorio",
    "spaceNumber": null,
    "order": 2,
    "originalName": "dormDPTO2.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Dormitorio de Departamento La Arbolada.",
    "sources": {
      "thumbnail": "/images/departamento/dormdpto2-thumbnail.webp",
      "mobile": "/images/departamento/dormdpto2-mobile.webp",
      "desktop": "/images/departamento/dormdpto2-desktop.webp",
      "large": "/images/departamento/dormdpto2-large.webp"
    }
  },
  {
    "id": "departamento-dormdpto3",
    "property": "departamento",
    "space": "Dormitorio",
    "spaceNumber": null,
    "order": 3,
    "originalName": "dormDPTO3.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Dormitorio de Departamento La Arbolada.",
    "sources": {
      "thumbnail": "/images/departamento/dormdpto3-thumbnail.webp",
      "mobile": "/images/departamento/dormdpto3-mobile.webp",
      "desktop": "/images/departamento/dormdpto3-desktop.webp",
      "large": "/images/departamento/dormdpto3-large.webp"
    }
  },
  {
    "id": "departamento-livingdpto1",
    "property": "departamento",
    "space": "Living",
    "spaceNumber": null,
    "order": 1,
    "originalName": "livingDPTO1.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Living de Departamento La Arbolada.",
    "sources": {
      "thumbnail": "/images/departamento/livingdpto1-thumbnail.webp",
      "mobile": "/images/departamento/livingdpto1-mobile.webp",
      "desktop": "/images/departamento/livingdpto1-desktop.webp",
      "large": "/images/departamento/livingdpto1-large.webp"
    }
  },
  {
    "id": "departamento-livingdpto2",
    "property": "departamento",
    "space": "Living",
    "spaceNumber": null,
    "order": 2,
    "originalName": "LivingDPTO2.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Living de Departamento La Arbolada.",
    "sources": {
      "thumbnail": "/images/departamento/livingdpto2-thumbnail.webp",
      "mobile": "/images/departamento/livingdpto2-mobile.webp",
      "desktop": "/images/departamento/livingdpto2-desktop.webp",
      "large": "/images/departamento/livingdpto2-large.webp"
    }
  },
  {
    "id": "departamento-verdedpto1",
    "property": "departamento",
    "space": "Entorno verde",
    "spaceNumber": null,
    "order": 1,
    "originalName": "verdeDPTO1.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Entorno verde de Departamento La Arbolada.",
    "sources": {
      "thumbnail": "/images/departamento/verdedpto1-thumbnail.webp",
      "mobile": "/images/departamento/verdedpto1-mobile.webp",
      "desktop": "/images/departamento/verdedpto1-desktop.webp",
      "large": "/images/departamento/verdedpto1-large.webp"
    }
  },
  {
    "id": "departamento-verdedpto2",
    "property": "departamento",
    "space": "Entorno verde",
    "spaceNumber": null,
    "order": 2,
    "originalName": "verdeDPTO2.HEIC",
    "width": 4032,
    "height": 3024,
    "orientation": "landscape",
    "alt": "Entorno verde de Departamento La Arbolada.",
    "sources": {
      "thumbnail": "/images/departamento/verdedpto2-thumbnail.webp",
      "mobile": "/images/departamento/verdedpto2-mobile.webp",
      "desktop": "/images/departamento/verdedpto2-desktop.webp",
      "large": "/images/departamento/verdedpto2-large.webp"
    }
  }
] as PropertyImage[];

export const casaImages = propertyImages.filter((image) => image.property === 'casa');
export const departamentoImages = propertyImages.filter((image) => image.property === 'departamento');
